### PR TITLE
Fix/Package related asset paths are legit now

### PR DESCRIPTION
**Pull request by Aqluse**
### Description of the Change

Fulfills issue given
https://github.com/BirjuVachhani/spider/issues/64
more precisely that kind of paths
https://docs.flutter.dev/development/ui/assets-and-images#bundling-of-package-assets

### Alternate Designs

No alternatives considered.

### Why Should This Be In Core?

As this kind of asset paths are legit in Dart ecosystem.

### Benefits

Ability to use the generator with package assets.

### Possible Drawbacks

No imminent drawbacks are expected.

### Verification Process

- How did you verify that all new functionality works as expected?
- How did you verify that all changed functionality works as expected?

I have run the generator for package and direct asset paths both. Output paths are whole being generated as expected. 

- How did you verify that the change has not introduced any regressions?

Just verified it by running generator for direct asset paths might be impacted by following changes. No other checks have been executed.

### Applicable Issues

https://github.com/BirjuVachhani/spider/issues/64

### CODE REVIEW

**Comment by BirjuVachhani** [comment]
@Aqluse Thank you for the PR! This looks good. I'll test it out later. Can you please add some tests for this?

**Comment by Aqluse** [comment]
@BirjuVachhani Unfortunately I am quite busy in nearest future.

**Comment by BirjuVachhani** [comment]
@Aqluse Can you provide me information about how to use it? I wanna test it with this asset package: https://pub.dev/packages/country_icons

**Comment by BirjuVachhani** [comment]
@Aqluse Seems like build is failing because of code formatting.

**Comment by BirjuVachhani** [comment]
Available in [v4.1.0](https://pub.dev/packages/spider/versions/4.1.0)

**Pull request merged**
